include/interface/agent.h: Stop using the same identifier for type and variable names.
In C, type names and variable names aren't strictly separated (they can for
example both be passed to the sizeof() function). This causes the error below
when -Wpedantic is enabled. Fix this by appending the _t suffix to typenames
like everybody else does.

```
In file included from ../src/../include/laik/ext.h:22:0,
                 from ../src/../include/laik.h:28,
                 from ../src/../include/laik-backend-mpi.h:21,
                 from ../examples/raytracer.cpp:47:
../src/../include/interface/agent.h:184:13: error: declaration of ‘double (* tag_laik_ext_profile_agent::gettime)()’ [-fpermissive]
     gettime gettime;
             ^~~~~~~
../src/../include/interface/agent.h:135:18: error: changes meaning of ‘gettime’ from ‘typedef double (* gettime)()’ [-fpermissive]
 typedef double (*gettime) (void);
                  ^~~~~~~
../src/../include/interface/agent.h:185:10: error: declaration of ‘int (* tag_laik_ext_profile_agent::peek)()’ [-fpermissive]
     peek peek;
          ^~~~
../src/../include/interface/agent.h:132:15: error: changes meaning of ‘peek’ from ‘typedef int (* peek)()’ [-fpermissive]
 typedef int (*peek) (void);
               ^~~~
```